updating all

diff --git a/AHA_fix b/AHA_fix
--- a/AHA_fix
+++ b/AHA_fix
@@ -130,32 +130,40 @@ sudo chmod -R 755 /Applications/iLog.app > /dev/null 2>&1
 sudo chmod -R 755 /Applications/AppleConnect.app > /dev/null 2>&1
 sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
 sleep 2
-sudo rm -rf /tmp/*.txt > /dev/null 2>&1
+
 echo                     
 echo Downloading AppleConnect...
-sudo jamf policy -event appleconnect > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-    echo "AppleConnect download FAILED!"
-    echo "Please download and install AppleConnect after system reboots"
-else
+sudo jamf policy -event appleconnect > /tmp/appleDL.txt
+appleDL=$(cat /tmp/appleDL.txt | sed -n 2p | awk '{print$1}')
+if [[ $appleDL == "Executing" ]]; then
     echo "AppleConnect Installed Successfully!!!"
-fi
-echo                                         
-java -version > /dev/null > 2>&1
-if [ $? -eq 0 ]; then
-    echo "JAVA detected..!"
 else
-    echo "No JAVA detected on system"
+    echo "AppleConnect Download FAILED!"
+fi
+sudo killall AppleConnect > /dev/null 2>&1
+
+echo          
+echo Checking JAVA on system...                               
+java -version > /dev/null 2>&1
+echo $? > /tmp/javaVER.txt
+javaVER=$(cat /tmp/javaVER.txt)
+if [[ $javaVER -eq 0 ]]; then
+    echo "JAVA Detected..!"
+else
+    echo "No JAVA detected"
     echo "Downloading JAVA..."
-    sudo jamf policy -event ilogjava > /dev/null 2>&1
-        if [ $? -eq 0 ]; then
+    sudo jamf policy -event ilogjava > /tmp/javaDL.txt
+    javaDL=$(cat /tmp/javaDL.txt | sed -n 2p | awk '{print$1}')
+        if [[ $javaDL == "Executing" ]]; then
             echo "JAVA Installed Successfully!!!"
         else
-            echo "JAVA download FAILED!"
-            echo "Please download and install JAVA after system reboots"
+            echo "JAVA Download FAILED!"
         fi
 fi
+javakill=$(pgrep -i java | grep -v ttys)
+sudo kill -9 $javakill > /dev/null 2>&1
 
+sleep 3
 echo                      
 echo Clearing Network Settings...
 sudo rm -rf /Library/Preferences/SystemConfiguration/* > /dev/null 2>&1
@@ -163,6 +171,48 @@ sudo rm -rf /Library/Preferences/com.apple.network* > /dev/null 2>&1
 sudo rm -rf /Library/Preferences/P2P* > /dev/null 2>&1
 sudo rm -rf /System/Library/NetworkServiceProxy/* > /dev/null 2>&1
 
+open -g /Applications/AppleConnect.app > /dev/null 2>&1
+echo $? > /tmp/appctest.txt
+sudo killall AppleConnect > /dev/null 2>&1
+appctest=$(cat /tmp/appctest.txt)
+if [[ $appctest -ne 0 ]]; then
+    function appcerror() {
+    sudo touch appcerror.py
+    sudo chmod 777 appcerror.py
+    echo '#!/usr/bin/python' >> appcerror.py
+    echo 'from Tkinter import *' >> appcerror.py
+    echo 'import tkMessageBox' >> appcerror.py
+    echo 'root = Tk()' >> appcerror.py
+    echo 'root.withdraw()' >> appcerror.py
+    echo 'tkMessageBox.showerror(title="Error!", message="AppleConnect download FAILED!\n\nPlease download and install AppleConnect manually.")' >> appcerror.py
+    }
+    appcerror
+    sudo ./appcerror.py > /dev/null 2>&1
+fi
+sudo rm -rf appcerror.py > /dev/null 2>&1
+
+java -version
+echo $? > /tmp/javatest.txt
+javakill=$(pgrep -i java | grep -v ttys)
+sudo kill -9 $javakill > /dev/null 2>&1
+javatest=$(cat /tmp/javatest.txt)
+if [[ $javatest -ne 0 ]]; then
+    function javaerror() {
+    sudo touch javaerror.py
+    sudo chmod 777 javaerror.py
+    echo '#!/usr/bin/python' >> javaerror.py
+    echo 'from Tkinter import *' >> javaerror.py
+    echo 'import tkMessageBox' >> javaerror.py
+    echo 'root = Tk()' >> javaerror.py
+    echo 'root.withdraw()' >> javaerror.py
+    echo 'tkMessageBox.showerror(title="Error!", message="JAVA download FAILED!\n\nPlease download and install JAVA manually.")' >> javaerror.py
+    }
+    javaerror
+    sudo ./javaerror.py > /dev/null 2>&1
+fi
+sudo rm -rf javaerror.py > /dev/null 2>&1
+
+sudo rm -rf /tmp/*.txt > /dev/null 2>&1
 echo
 echo              
 echo C O M P L E T E D !
@@ -180,6 +230,8 @@ do
     else
         echo $i..
         sleep 1
+        javakill=$(pgrep -i java | grep -v ttys)
+        sudo kill -9 $javakill > /dev/null 2>&1
     fi
 done
 
diff --git a/fortiReset b/fortiReset
--- a/fortiReset
+++ b/fortiReset
@@ -11,7 +11,7 @@ mDNS1=$(pgrep mDNSResponder | sed -n 1p)
 mDNS2=$(pgrep mDNSResponder | sed -n 2p)
 FortiPS=$(ps aux | grep -i Forti | grep -v ttys | awk '{print $2}' > /tmp/FortiPS.txt)
 
-declare Forti=(`cat /tmp/FortiPS.txt`)
+declare FClient=(`cat /tmp/FortiPS.txt`)
 
 sudo tar -cf ~/Desktop/Forti.bak /Library/Application\ Support/Fortinet/FortiClient/conf/vpn.plist
 echo Backing-up FortiClient profile...
@@ -22,7 +22,7 @@ countkForti=$(echo ${#Forti[*]})
 
 for (( i=0; i<$countkForti; i++ ));
 do
-    sudo kill -9 ${Forti[$i]} > /dev/null 2>&1
+    sudo kill -9 ${FClient[$i]} > /dev/null 2>&1
 done
 
 sudo killall FortiClient > /dev/null 2>&1
@@ -36,10 +36,7 @@ sudo rm -rf /Library/LaunchDaemons/com.forti* > /dev/null 2>&1
 sudo rm -rf /Library/LaunchAgents/com.forti* > /dev/null 2>&1
 echo Removing all FortiClient libraries...
 sudo rm -rf ~/Library/Application\ Support/Forti* > /dev/null 2>&1
-sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/Logs > /dev/null 2>&1
-sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/data > /dev/null 2>&1
-sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/ipsec > /dev/null 2>&1
-sudo rm -rf /Library/Application\ Support/Fortinet/FortiClient/tmp > /dev/null 2>&1
+sudo rm -rf /Library/Application\ Support/Forti* > /dev/null 2>&1
 echo Removing all FortiClient settings...
 sudo rm -rf ~/Library/Application\ Support/com.forti* > /dev/null 2>&1
 sudo rm -rf /Library/Application\ Support/com.forti* > /dev/null 2>&1
@@ -54,6 +51,33 @@ sudo rm -rf ~/Library/Caches/* > /dev/null 2>&1
 sudo rm -rf /System/Library/CacheDelete/* > /dev/null 2>&1
 echo Removing Temporary Files...
 sudo rm -rf ~/.temp* > /dev/null 2>&1
+echo                     
+echo Downloading FortiClient...
+sudo jamf policy -event forticlient > /tmp/fortiDL.txt
+fortiDL=$(cat /tmp/fortiDL.txt | sed -n 2p | awk '{print$1}')
+if [[ $fortiDL == "Executing" ]]; then
+    echo "FortiClient Installed Successfully!!!"
+else 
+	echo "JAMF link is down redirecting to forticlient.com..."
+	echo                                  
+	cd ~/Desktop
+	curl -O https://d3gpjj9d20n0p3.cloudfront.net/forticlient/downloads/FortiClient_5.6.1.723_macosx.dmg
+	echo Download Complete...
+	echo Mounting Disk Image...
+	ls /Volumes | cut -d @ -f1 > /tmp/Volumes.txt
+	target=$(cat /tmp/Volumes.txt)
+	sudo hdiutil mount ~/Desktop/FortiClient_5.6.1.723_macosx.dmg
+	sleep 2
+	echo Installing FortiClient...
+	sudo installer -pkg /Volumes/FortiClient/Install.mpkg -tgt /Volumes/"$target"
+	echo Unmounting Disk Image...
+	sudo hdiutil unmount /Volumes/FortiClient
+	sleep 2
+	echo sudo rm -rf ~/Desktop/FortiClient_5.6.1.723_macosx.dmg
+fi
+sudo killall FortiClient > /dev/null 2>&1
+
+echo                 
 echo Importing FortiClient profile...
 sudo tar -xf ~/Desktop/Forti.bak -C /
 sleep 5
@@ -64,6 +88,7 @@ sudo chown -R root:wheel /Applications/FortiClient.app > /dev/null 2>&1
 sleep 1
 echo Changing Permissions...
 sudo chmod -R 755 /Applications/FortiClient.app > /dev/null 2>&1
+
 sudo rm -rf /tmp/*.txt > /dev/null 2>&1
 
 echo           
@@ -71,5 +96,33 @@ echo C O M P L E T E D !
 echo                          
 echo  
 
-open /Applications/FortiClient.app
-sudo killall Terminal
+open /Applications/FortiClient.app > /dev/null 2>&1
+if [[ $? -ne 0 ]]; then
+	function error() {
+	sudo touch error.py
+	sudo chmod 777 error.py
+	echo '#!/usr/bin/python' >> error.py
+	echo 'from Tkinter import *' >> error.py
+	echo 'import tkMessageBox' >> error.py
+	echo 'root = Tk()' >> error.py
+	echo 'root.withdraw()' >> error.py
+	echo 'tkMessageBox.showerror(title="Error!", message="FortiClient download FAILED!\n\nPlease download and install FortiClient manually.")' >> error.py
+	}
+	error
+	sudo ./error.py > /dev/null 2>&1
+fi
+
+sudo rm -rf error.py
+echo Closing Terminal in 5 secs...
+for (( i=5; i>=1; i-- ));
+do
+    if [[ i -eq 1 ]]; then
+        echo
+        echo closing NOW.. !
+        echo            
+        sudo killall Terminal
+    else
+        echo $i..
+        sleep 1
+    fi
+done
